site_name: 文档制作
theme: 
  name: readthedocs
  highlightjs: true

# extra_javascript:
#   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - css/extra.css

# Extensions
markdown_extensions:
  - mdx_truly_sane_lists

nav:
- Home: 
  - 简介: index.md
- 文档制作:
  - mkdocs: '文档制作/mkdocs使用说明.md'
  - Sphinx + GitHub + ReadtheDocs: '文档制作/Sphinx + GitHub + ReadtheDocs.md'
- About: 
  - 关于: about.md